//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""MouseInput"",
            ""id"": ""df7fdcdc-5816-40b9-8163-dfe9eba8b3d9"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""7c88bc3f-c54f-4069-ac1a-c75bc0febda2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left_Click"",
                    ""type"": ""Button"",
                    ""id"": ""f43152c8-f1c5-41a5-9b26-9dd4ad656e86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba32b5ca-309b-476e-9411-1f282e763918"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c2fe177-92ce-4c9c-a433-6d4a9fb5b17d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left_Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MouseInput
        m_MouseInput = asset.FindActionMap("MouseInput", throwIfNotFound: true);
        m_MouseInput_Position = m_MouseInput.FindAction("Position", throwIfNotFound: true);
        m_MouseInput_Left_Click = m_MouseInput.FindAction("Left_Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MouseInput
    private readonly InputActionMap m_MouseInput;
    private IMouseInputActions m_MouseInputActionsCallbackInterface;
    private readonly InputAction m_MouseInput_Position;
    private readonly InputAction m_MouseInput_Left_Click;
    public struct MouseInputActions
    {
        private @InputControls m_Wrapper;
        public MouseInputActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_MouseInput_Position;
        public InputAction @Left_Click => m_Wrapper.m_MouseInput_Left_Click;
        public InputActionMap Get() { return m_Wrapper.m_MouseInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseInputActions set) { return set.Get(); }
        public void SetCallbacks(IMouseInputActions instance)
        {
            if (m_Wrapper.m_MouseInputActionsCallbackInterface != null)
            {
                @Position.started -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnPosition;
                @Left_Click.started -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnLeft_Click;
                @Left_Click.performed -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnLeft_Click;
                @Left_Click.canceled -= m_Wrapper.m_MouseInputActionsCallbackInterface.OnLeft_Click;
            }
            m_Wrapper.m_MouseInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Left_Click.started += instance.OnLeft_Click;
                @Left_Click.performed += instance.OnLeft_Click;
                @Left_Click.canceled += instance.OnLeft_Click;
            }
        }
    }
    public MouseInputActions @MouseInput => new MouseInputActions(this);
    public interface IMouseInputActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnLeft_Click(InputAction.CallbackContext context);
    }
}
